### ISSUE TITLE
Package Control

### ISSUE THREAD

**Issue by chriskacerguis** [braver/SublimeRetina#2]
Hello,

Your theme is great!  Any chance you can submit your app to Package Control for easier install?  https://packagecontrol.io/docs/submitting_a_package

**Comment by braver** [comment]
I thought about that, but I'm reusing original assets and as such I'm not even sure it's ok to open source it. I tried to contact Jon and Wbond, but no response yet. Don't want to step on anyone's toes, etc. So I'm not sure what to do with the theme.

**Comment by chriskacerguis** [comment]
Certainly makes sense.  I'd say you made an honest effort to do that, and just to add it...worst case they ask you to take it down.

**Comment by braver** [comment]
I guess you're right. Packagecontrol is moderated anyway, so especially now that @wbond is on board at ST it should show up on their radar anyway.

**Comment by chriskacerguis** [comment]
Also, I found this from the ST forums...so, it is there too :)

Again, great work.

**Comment by braver** [comment]
Well, the PR is in at package control.
