### ISSUE TITLE
Missing icon after ST3 UI refresh

### ISSUE THREAD

**Issue by KM4YRI** [braver/SublimeRetina#4]
I'm a new user to the SublimeRetina theme.  I do not have a retina display, however, it has become useful to some of us after the new UI refresh that was released today for ST3.0 out-of-beta.  They pushed a retina-compatible version that has completely done away with the old tabs, replacing them with something straight out of Google's Material Design guidelines.

I asked [here in their technical support forum](https://forum.sublimetext.com/t/ui-refresh/31245/9) if there was an existing theme that brought back the 'classic' look, and another user recommended SublimeRetina.

I installed it today and I think that this is a new issue (see image below), having to due with the new theme replacing icons that no longer exist, or something to that effect.  Others in the support forum have reported similar issues today after the release, with third-party themes.

![image](https://user-images.githubusercontent.com/24699588/30383056-c33918e6-986e-11e7-9c86-f827fbb793ca.png)

(See the bottom-left corner, near 'line 1 column 1'.

Can you replicate this issue?  I do have a few plugins installed but nothing that messes with the theme or color scheme.

**Comment by braver** [comment]
> and another user

Yeah, that was probably me. I originally intended to drop support for this as 3.0 went live. I thought it would have been pulled from package control actually, but 🤷‍♂️  But I can totally get how people want the old style back so perhaps that's a good reason for this to stick around.

I think it leaned on assets being available in the default theme, and those are of course gone now. I should be able to replicate and fix that. Perhaps later today... I'll have to see.

**Comment by KM4YRI** [comment]
> Yeah, that was probably me.

Ohh damn, completely missed that connection there :+1:  Well thanks for making the plugin in the first place, and thanks for the quick reply over on the ST3 tech support forum.  The staff over there seem pretty apathetic and unhelpful to issues like this, they genuinely don't seem to care.

>  I originally intended to drop support for this as 3.0 went live.  [...]  I should be able to replicate and fix that. Perhaps later today... I'll have to see.

No worries.  I know how much of a bear it can be to support older projects that are becoming less relevant.  

If you're considering abandoning it, I'd be happy to fork it and release it as 'Sublime Text Classic' or something to that effect.  That name would probably be more appropriate anyway.  I've modified plugins but never themes although I don't assume that it would be that difficult.  It really just comes down to time.

**Comment by braver** [comment]
> The staff over there seem pretty apathetic and unhelpful to issues like this, they genuinely don't seem to care.

Well, let's call it focussed ;) But you really cannot make GUI changes without (a lot of and usually very ehm... expressive) negative response, no matter how valid. Will Bond is a genuinely nice guy though, so I guess it's just his coping mechanism.

> If you're considering abandoning it, I'd be happy to fork it and release it as 'Sublime Text Classic' or something to that effect. 

I should look into the status on package control before renaming. But it's just a name, a description update might be enough.

> I've modified plugins but never themes although I don't assume that it would be that difficult. 

It is super easy, just a static data file with some references to properties and assets. Also, the API basically never changes so it's super low maintenance (unless a 3.0 release happens of course 🙄 )

If you want I can add you as a collaborator, so if you get around to fixing things you can just go ahead and make it available to everyone?

**Comment by KM4YRI** [comment]
> Well, let's call it focussed ;) But you really cannot make GUI changes without (a lot of and usually very ehm... expressive) negative response, no matter how valid.

I'm not the only one flying off the handles today.  Their abrupt changes today have broken a number of important plugins and themes, at least from what I can see in the forum.  Maybe they should have just kept it in beta (or better yet, alpha, non-downloadable from the app) until these sorts of issues are worked out?

> Will Bond is a genuinely nice guy though

OK, but I don't really buy his excuse that he gave that they don't have access to the resource files.  Had he just said that they didn't have the time or didn't give a fuck, I would have accepted that.  But obviously your SublimeRetina theme proves that it wasn't that difficult to re-create the resource files.  Seems very disingenuous on his part to give that answer.  I'm sure if they'd have asked you nicely they could have been made available royalty free to them; I mean they're based on software that they wrote, it's their artwork, even if it's gone through some Photoshop deconstruction.  Nope, the issue is that they're jumping onto the 'modern UI' bandwagon with zero regard for everyone that (A) thinks it's overplayed at this point or (B) just don't like change for the sake of change.  

> I should look into the status on package control before renaming. But it's just a name, a description update might be enough.

That's a good approach.

> If you want I can add you as a collaborator, so if you get around to fixing things you can just go ahead and make it available to everyone?

Nah, I'm fine working through pull requests as long as the original maintainer is still around and kicking.  Hopefully if you've got time to at least re-create the issue then it can at least be confirmed to be something that needs attention.  I just read something about clearing out a cache.  I tried that and still not fixed.  So I'm assuming it's looking for a resource that's not there in the updated version.

**Comment by braver** [comment]
> Maybe they should have just kept it in beta (or better yet, alpha, non-downloadable from the app) until these sorts of issues are worked out?

Yeah, I kinda expected a public beta of this build to get some extra exposure to packages that need updating. But on the other hand, the builds of the past year were mostly cosmetic and bug fixes, and package developers have been able to test the last dev build for months. The architecture of ST allows so many customisations that it's impossible to cover everything. 

> But obviously your SublimeRetina theme proves that it wasn't that difficult to re-create the resource files. 

Eh, you're underestimating the time that went into this.

>  I'm sure if they'd have asked you nicely they could have been made available royalty free to them

Oh, I offered it to them.

I totally get that though. Sublime needed a new look, new assets and probable an assets toolchain to move forward and they cannot afford to maintain multiple UI's. Also, the old UI is available for everyone to unpack from Sublime Text 2, so it's there if you want it. And there is this repo. They lean on the community to create options like this, and it's probably a good idea. They need to be super picky about what to work with only 2 guys, it's not Github or Microsoft.

**Comment by KM4YRI** [comment]
> Sublime needed a new look,

Not to go too far off-tangent in a github issue, but I gotta disagree there.  Who actually considers Sublime Text to look outdated?  Honest question.

Needs a new look compared to what?  Notepad++?  UltraEdit? TextWrangler for Mac?   It pretty much IS the new look compared to these old, clunky, outdated text editors.  

I'm being 100% honest here, if they would have kept it as-is previous to today, not a single person would want to abandon it or choose something else because of its looks.  I can't think of a single person that would ever think that it's ugly or in need of a facelift.  

What editor out there looks *more* modern?  If you list the ones that come even a little bit close, they're probably just clones of ST3, at least superficially.

**Comment by braver** [comment]
> Who actually considers Sublime Text to look outdated? Honest question.

The guy who maintains it. It's his call. 🤷‍♂️

**Comment by TheJaredWilcurt** [comment]
Here are some graphics to place in that spot:

1x
![1x](https://user-images.githubusercontent.com/4629794/30397581-5a3df79e-989b-11e7-8f5f-ec3bc201d96c.png)
2x
![2x](https://user-images.githubusercontent.com/4629794/30397585-5d6000e8-989b-11e7-91a9-62eb5d6ba4a0.png)
4x
![4x](https://user-images.githubusercontent.com/4629794/30397600-5ece006a-989b-11e7-9c93-4276ea28cbf8.png)

Also attached the PSD file (zipped).

[4x.psd.zip](https://github.com/braver/SublimeRetina/files/1300760/4x.psd.zip)

**Comment by braver** [comment]
Thanks, I think I got it though. Already had the assets, but it was inheriting assets. I think the 1.0.2 should roll out via PC soon with the fix.

**Comment by TheJaredWilcurt** [comment]
So can you back up the assets from a previous version then and store them in this repo?

**Comment by braver** [comment]
Well, anyone can get the old default theme from an old build, but I don't think the license allows redistribution via a package. So if you're all set on keeping the old UI you can extract it from the previous beta build yourself.

**Comment by KM4YRI** [comment]
@braver, about how long does your latest commit take to propagate to [packagecontrol.io](https://packagecontrol.io/packages/Theme%20-%20Retina)?

Oh, on another note, look how your downloads shot up today after the new version dropped: 

![image](https://user-images.githubusercontent.com/24699588/30398476-81cc10e0-989e-11e7-8bd5-e946574904f6.png)

**Comment by braver** [comment]
Usually more like minutes than hours. I originally pulled it from PC so I'm not sure it will even pick up on the update until the revert that puts it back is merged. So... wait and see, or clone this into your Packages dir.
